[package]
name = "tiled"
version = "0.14.0"
description = "A rust crate for loading maps created by the Tiled editor"
categories = ["game-development"]
keywords = ["gamedev", "tiled", "tmx", "map"]
repository = "https://github.com/mapeditor/rs-tiled"
readme = "README.md"
license = "MIT"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]
edition = "2018"
include = ["src/**/*.rs", "README.md", "LICENSE", "CHANGELOG.md"]

[features]
default = ["zstd"]
wasm = ["zstd/wasm"]
world = ["regex", "serde", "serde_json", "serde_regex"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[[example]]
name = "sfml"
path = "examples/sfml/main.rs"

[[example]]
name = "ggez"
path = "examples/ggez/main.rs"

[dependencies]
base64 = "0.22.1"
xml-rs = "0.8.4"
zstd = { version = "0.13.3", optional = true, default-features = false }
flate2 = "1.0.28"
serde = { version = "1.0.216", optional = true }
serde_json = { version = "1.0.133", optional = true }
serde_regex = { version = "1.1.0", optional = true }
regex = { version = "1.11.1", optional = true }

[dev-dependencies.sfml]
version = "0.21.0"
features = ["graphics"]

[dev-dependencies.ggez]
version = "0.9.3"
